version: 2
jobs:
  build:
    working_directory: ~/steganogan
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
        command: echo 'sudo apt-get install lzma'
      - run:
        command: sudo apt-get install lzma
      - run: tox
